### ISSUE TITLE
Small error in README and a small request

### ISSUE THREAD

**Issue by amundgr** [Eiyeron/py_aseprite#1]
The example in the README.org has the following example:

~~~~{.python}
from aseprite import AsepriteFile

with open('my_file.aseprite', r) as f:
    parsed_file = AsepriteFile(f.read())
~~~~

I think the second line should be:
~~~~{.python}
with open('my_file.aseprite','rb') as f:
~~~~
At least thats what i had to do to make it run and be able to read bytes from file.

Anyway, thanks for your work, saved me some time.

**Comment by Eiyeron** [comment]
Thanks for the notice and sorry for the delay. Glad to hear it was also helpful to you too.
